# -*- coding: utf-8 -*-
{
    "name": "chc_cds_planning",
    "summary": "Planning CDS",
    "description": """Outil de gestion de planning - Outil dédié au CDS du CHC.""",
    "author": "CHBUS & KEHOA",
    "website": "https://www.chc.be",
    "license": "LGPL-3",
    "category": "Uncategorized",
    "version": "0.1.6",
    "depends": ["base", "web", "hr", "portal", "hr_holidays", "website", "mail"],
    "data": [
        "security/init_groups.xml",
        "security/rules.xml",
        "security/ir.model.access.csv",
        "views/planning_weekly_views.xml",
        "views/planning_employee_views.xml",
        "views/planning_permanence_type_views.xml",
        "views/planning_site_views.xml",
        "views/l1_guard_calendar_views.xml",
        "views/planning_template_views.xml",
        "views/planning_templates.xml",
        "views/planning_report.xml",
        "views/monthly_planning_generator_views.xml",
        "views/planning_stats_views.xml",
        "wizard/planning_template_wizard_views.xml",
        "wizard/planning_confirm_override_wizard_views.xml",
        "wizard/public_holidays_import_wizard_views.xml",
        "wizard/sickness_replacement_wizard_views.xml",
        "views/planning_menu_views.xml",
        "data/init_site_perm_data.xml",
        "data/init_users_data.xml",
        # Seeds métier archivés (contenu commenté dans les fichiers) :
        # ne plus les recharger au -u pour éviter d'écraser les données prod.
        # "data/init_employee_data.xml",
        # "data/init_l1_guard_calendar_data.xml",
        # "data/init_employee_unavailability_data.xml",
        "data/default_planning_data.xml",
        "data/hr_leave_type_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # CSS Files
            "chc_cds_planning/static/src/css/planning_visual.css",
            # "chc_cds_planning/static/src/css/planning_context_menu.css",
            # JavaScript Files - ORDRE IMPORTANT !
            # "chc_cds_planning/static/src/js/planning_context_menu.js",
            "chc_cds_planning/static/src/js/planning_visual.js",
            "chc_cds_planning/static/src/js/planning_visual_client_action.js",
            "chc_cds_planning/static/src/js/time_off_calendar_patch.js",
            "chc_cds_planning/static/src/xml/planning_visual_client_action.xml",
        ],
    },
    "application": True,
}
